apiVersion: batch/v1
kind: Job
metadata:
  name: jmeter-solr-load-test
  namespace: load-testing
spec:
  ttlSecondsAfterFinished: 604800  # clean up after 7 days
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: jmeter
          image: justb4/jmeter:5.6.3
          args:
            - "-n"
            - "-t"
            - "/test-plans/solr_test_plan.jmx"
            - "-Jhost=solr.solr.svc.cluster.local"
            - "-Jport=8983"
            - "-Jsolr_core=4614dab5-cc11-45ca-8c87-8ac9f38ecc34"  # update per run if needed
            - "-Jkeyword_file_full_path=/keywords/keywords.csv"
            - "-Jkw_expected_result_count=0"
            - "-Jsitemap_expected_result_count=0"
            - "-e"
            - "-l"
            - "/results/test-report.jtl"
            - "-o"
            - "/results/html-report"
          volumeMounts:
            - name: results
              mountPath: /results
            - name: keywords
              mountPath: /keywords
            - name: test-plans
              mountPath: /test-plans
      volumes:
        - name: results
          persistentVolumeClaim:
            claimName: jmeter-results
        - name: keywords
          configMap:
            name: jmeter-keywords
        - name: test-plans
          configMap:
            name: jmeter-test-plans
