apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jmeter-results
  namespace: load-testing
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 20Gi
